### ISSUE TITLE
Cordium Axe & Lustrian Axe share the same config setting.

### ISSUE THREAD

**Issue by Norfried** [Jboymercs/end_expansion_final#13]
I'm not sure if this is intentional, but these two axes always have the same damage number no matter what the setting is set to.

Any chance these two could be separated into their own settings? That would be much appreciated!

![CordiumAxeBug](https://github.com/user-attachments/assets/0548dfda-2ca2-40a9-b5af-e7f91c3d017d)
![2024-12-16_00 38 34](https://github.com/user-attachments/assets/c539d83b-bff4-4e2f-9d76-cfa863e14972)
![2024-12-16_00 38 28](https://github.com/user-attachments/assets/8847bb4b-19ae-4a85-b163-e75fb29f290b)

**Comment by Jboymercs** [comment]
Will have this fixed soon, thank you!

**Comment by Jboymercs** [comment]
Fixed in End Expansion Hot Fix 1.2! added an option for the lustrian axe, big whoopsies on my part
