### ISSUE TITLE
Conflict with extra golems

### ISSUE THREAD

**Issue by Kuwagumo** [Jboymercs/end_expansion_final#5]
While playing on my pack, notied that the golem manual from extra golems (7.1.9) has it's name replaced by the guide from this mod. The contents, surprisingly, do not seem to change. (End expansion is version 0.8, to clarify).

**Comment by Jboymercs** [comment]
I'll have a look into it, thank you!

**Comment by Jboymercs** [comment]
After looking into it, it's just a lang key issue, nothing harmful or crash worthy. Next time I update the mod to 1.0, It'll be fixed. Also, I'd reccomend updating End Expansion to 0.9, as a bunch of multiplayer stuff plus an experimental sky box has been added to the end. Thank you for reporting this!
